project:
  type: website

website:
  title: "TGI-OS Training"
  sidebar:
    contents:
      - index.qmd
      - section: "Session 5: BHM"
        contents: session-bhm/*
      - section: "Session 4: PTS"
        contents: session-pts/*
      - section: "Session 3: TGI-OS"
        contents: session-jm/*
      - section: "Session 2: OS"
        contents: session-os/*
      - section: "Session 1: TGI"
        contents: session-tgi/*
    tools:
      - icon: github
        href: https://rconis.github.io/tgi-os-training/
  repo-url: https://github.com/RCONIS/tgi-os-training/
  repo-actions: [edit, issue]
  
format:
  html:
    theme:
      - sandstone
      - custom.scss
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    toc: true
    toc_float: true

date-format: iso
